env: "local" # local, dev, prod
storage_path: ""
http_Server :
  address: "localhost:8080"
  timeout: 4s  # время на чтение и такое же время на отправку ответа
  idle_timeout: 60s # время жизни открытого соединения от клиента ( и на нем будут обрабатываться все запросы)
